# Generated by Django 3.0 on 2020-01-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='posted_by',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=40, null=True),
        ),
    ]
